### ISSUE TITLE
Error from HUE-Plugin

### ISSUE THREAD

**Issue by redbull290** [nitaybz/homebridge-network-presence#7] opened 2020-12-21 16:10 UTC
After I installed the plugin, I received many errors from the HUE plugin in the log file, such as 'Heartbeat XXX, Drift XXX'.
Could that possibly indicate a resource problem? Or is my ping interval set too short at 10 seconds?

**Comment by nitaybz** [comment] 2020-12-23 13:48
it doesn't sound like an error... can you share some logs?

**Comment by notorioustubze** [comment] 2020-12-23 15:25
I can confirm I'm getting multiple heartbeat drift warning from the Philips Hue plugin since installing Network presence.
[23/12/2020, 15:18:02] [Hue] heartbeat 1474, drift 280
[23/12/2020, 15:22:45] [Hue] heartbeat 1757, drift 263

**Comment by nitaybz** [comment] 2020-12-28 10:59
Please test v1.2.0 and report back

**Comment by notorioustubze** [comment] 2020-12-28 11:00
Thank you for the update I have installed it and will let you know if things improve.

**Comment by notorioustubze** [comment] 2020-12-30 08:13
Hey, been checking the logs and so far so good whatever you changed appears to be working. So thank you! 😁

**Comment by nitaybz** [comment] 2020-12-30 11:17
Glad it helped :)
Closing...

**Closed by nitaybz** 2020-12-30 11:17 UTC
